chore: Improve GH action build

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,22 +1,53 @@
 name: Build
 
+env:
+  # https://github.com/actions/virtual-environments/issues/1499
+  MAVEN_CLI_OPTS: '-ntp --batch-mode --errors --fail-at-end --show-version -Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Dmaven.wagon.http.retryHandler.count=3 -Dstyle.color=always'
+
 on:
-    pull_request:
-    merge_group:
-    push:
+  # allow to manual run the action
+  workflow_dispatch: {}
+  pull_request: {}
+  merge_group: {}
+  push:
+    branches:
+      - develop
+    tags:
+      - '*'
+
+permissions:
+  contents: write
+  # For junit report
+  checks: write
+  pull-requests: write
 
 jobs:
-    build:
-        name: Build
-        runs-on: ubuntu-latest
-        steps:
-            -   uses: actions/checkout@v4
+  build:
+    name: Build
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
 
-            -   name: Set up JDK 17
-                uses: actions/setup-java@v4
-                with:
-                    distribution: 'temurin'
-                    java-version: 17
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: 17
 
-            -   name: Build with Maven
-                run: ./mvnw clean package --batch-mode
+      - name: Build with Maven
+        run: |
+          ./mvnw ${MAVEN_CLI_OPTS} clean verify
+          ./mvnw javadoc:javadoc
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/*-reports/TEST-*.xml'
+
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v4.6.0
+        with:
+          file: "${{ github.workspace }}/spi/target/jacoco.xml"
+          token: ${{ secrets.CODECOV_TOKEN }}
+          fail_ci_if_error: ${{ !startsWith(github.event.ref, 'refs/tags/v') }}
